// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// note this is
type AuthMethod int32

const (
	AuthMethod_UNSPECIFIED AuthMethod = 0
	AuthMethod_FormEdit    AuthMethod = 1 // input form
	AuthMethod_ScanQrcode  AuthMethod = 2 // scan code
	AuthMethod_OAuth2      AuthMethod = 3 // OAuth2
)

// Enum value maps for AuthMethod.
var (
	AuthMethod_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "FormEdit",
		2: "ScanQrcode",
		3: "OAuth2",
	}
	AuthMethod_value = map[string]int32{
		"UNSPECIFIED": 0,
		"FormEdit":    1,
		"ScanQrcode":  2,
		"OAuth2":      3,
	}
)

func (x AuthMethod) Enum() *AuthMethod {
	p := new(AuthMethod)
	*p = x
	return p
}

func (x AuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_proto_enumTypes[0].Descriptor()
}

func (AuthMethod) Type() protoreflect.EnumType {
	return &file_proto_plugin_proto_enumTypes[0]
}

func (x AuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMethod.Descriptor instead.
func (AuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type Status_State int32

const (
	Status_UNSPECIFIED Status_State = 0
	Status_Success     Status_State = 1
	Status_Fail        Status_State = 2
	Status_AuthFinish  Status_State = 3
	Status_AuthExpired Status_State = 4
)

// Enum value maps for Status_State.
var (
	Status_State_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "Success",
		2: "Fail",
		3: "AuthFinish",
		4: "AuthExpired",
	}
	Status_State_value = map[string]int32{
		"UNSPECIFIED": 0,
		"Success":     1,
		"Fail":        2,
		"AuthFinish":  3,
		"AuthExpired": 4,
	}
)

func (x Status_State) Enum() *Status_State {
	p := new(Status_State)
	*p = x
	return p
}

func (x Status_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_proto_enumTypes[1].Descriptor()
}

func (Status_State) Type() protoreflect.EnumType {
	return &file_proto_plugin_proto_enumTypes[1]
}

func (x Status_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_State.Descriptor instead.
func (Status_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{2, 0}
}

type FileEntry_FileType int32

const (
	FileEntry_FileTypeUNSPECIFIED FileEntry_FileType = 0
	FileEntry_FileTypeDir         FileEntry_FileType = 1
	FileEntry_FileTypeFile        FileEntry_FileType = 2
)

// Enum value maps for FileEntry_FileType.
var (
	FileEntry_FileType_name = map[int32]string{
		0: "FileTypeUNSPECIFIED",
		1: "FileTypeDir",
		2: "FileTypeFile",
	}
	FileEntry_FileType_value = map[string]int32{
		"FileTypeUNSPECIFIED": 0,
		"FileTypeDir":         1,
		"FileTypeFile":        2,
	}
)

func (x FileEntry_FileType) Enum() *FileEntry_FileType {
	p := new(FileEntry_FileType)
	*p = x
	return p
}

func (x FileEntry_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileEntry_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_proto_enumTypes[2].Descriptor()
}

func (FileEntry_FileType) Type() protoreflect.EnumType {
	return &file_proto_plugin_proto_enumTypes[2]
}

func (x FileEntry_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileEntry_FileType.Descriptor instead.
func (FileEntry_FileType) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{3, 0}
}

// video display VideoResolution
type FileResource_VideoResolution int32

const (
	FileResource_VideoResolutionUnspecified FileResource_VideoResolution = 0
	FileResource_VideoResolutionOriginal    FileResource_VideoResolution = 1 // Origin
	FileResource_VideoResolutionHD          FileResource_VideoResolution = 2 // 720P high defintion
	FileResource_VideoResolutionFHD         FileResource_VideoResolution = 3 // 1080P full high defintion
	FileResource_VideoResolutionQHD         FileResource_VideoResolution = 4 // 2K  quad high defintion
	FileResource_VideoResolutionUHD         FileResource_VideoResolution = 5 // 4K ultra high defintion
)

// Enum value maps for FileResource_VideoResolution.
var (
	FileResource_VideoResolution_name = map[int32]string{
		0: "VideoResolutionUnspecified",
		1: "VideoResolutionOriginal",
		2: "VideoResolutionHD",
		3: "VideoResolutionFHD",
		4: "VideoResolutionQHD",
		5: "VideoResolutionUHD",
	}
	FileResource_VideoResolution_value = map[string]int32{
		"VideoResolutionUnspecified": 0,
		"VideoResolutionOriginal":    1,
		"VideoResolutionHD":          2,
		"VideoResolutionFHD":         3,
		"VideoResolutionQHD":         4,
		"VideoResolutionUHD":         5,
	}
)

func (x FileResource_VideoResolution) Enum() *FileResource_VideoResolution {
	p := new(FileResource_VideoResolution)
	*p = x
	return p
}

func (x FileResource_VideoResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileResource_VideoResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_proto_enumTypes[3].Descriptor()
}

func (FileResource_VideoResolution) Type() protoreflect.EnumType {
	return &file_proto_plugin_proto_enumTypes[3]
}

func (x FileResource_VideoResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileResource_VideoResolution.Descriptor instead.
func (FileResource_VideoResolution) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5, 0}
}

type FileResource_ResourceType int32

const (
	FileResource_MediaResourceTypeUNSPECIFIED FileResource_ResourceType = 0
	FileResource_Video                        FileResource_ResourceType = 1
	FileResource_Subtitle                     FileResource_ResourceType = 2
	FileResource_Audio                        FileResource_ResourceType = 3
)

// Enum value maps for FileResource_ResourceType.
var (
	FileResource_ResourceType_name = map[int32]string{
		0: "MediaResourceTypeUNSPECIFIED",
		1: "Video",
		2: "Subtitle",
		3: "Audio",
	}
	FileResource_ResourceType_value = map[string]int32{
		"MediaResourceTypeUNSPECIFIED": 0,
		"Video":                        1,
		"Subtitle":                     2,
		"Audio":                        3,
	}
)

func (x FileResource_ResourceType) Enum() *FileResource_ResourceType {
	p := new(FileResource_ResourceType)
	*p = x
	return p
}

func (x FileResource_ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileResource_ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_proto_enumTypes[4].Descriptor()
}

func (FileResource_ResourceType) Type() protoreflect.EnumType {
	return &file_proto_plugin_proto_enumTypes[4]
}

func (x FileResource_ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileResource_ResourceType.Descriptor instead.
func (FileResource_ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5, 1}
}

// plugin info from toml
// zip
// {plugin}.toml
// ${id}.wasm
// ${id}.png
type DriverPluginConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // @gotags: toml:"id" gorm:"primaryKey"
	Name         string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // @gotags: toml:"name" // driver plugin name,file must use ${name}.wasm
	Desc         string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`                                     // @gotags: toml:"desc" // driver plugin desc
	Author       []string `protobuf:"bytes,4,rep,name=author,proto3" json:"author,omitempty"`                                 // @gotags: toml:"author" gorm:"type:bytes;serializer:json"
	Version      string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                               // @gotags: toml:"version"
	ReleasedTime string   `protobuf:"bytes,6,opt,name=released_time,json=releasedTime,proto3" json:"released_time,omitempty"` // @gotags: toml:"released_time"
	Url          string   `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`                                       // @gotags: toml:"url"
	Icon         string   `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`                                     // @gotags: toml:"icon"
	Changelog    []string `protobuf:"bytes,9,rep,name=changelog,proto3" json:"changelog,omitempty"`                           // @gotags: toml:"released_changelog" gorm:"type:bytes;serializer:json"
}

func (x *DriverPluginConfig) Reset() {
	*x = DriverPluginConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverPluginConfig) ProtoMessage() {}

func (x *DriverPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverPluginConfig.ProtoReflect.Descriptor instead.
func (*DriverPluginConfig) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *DriverPluginConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverPluginConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverPluginConfig) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *DriverPluginConfig) GetAuthor() []string {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *DriverPluginConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DriverPluginConfig) GetReleasedTime() string {
	if x != nil {
		return x.ReleasedTime
	}
	return ""
}

func (x *DriverPluginConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DriverPluginConfig) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *DriverPluginConfig) GetChangelog() []string {
	if x != nil {
		return x.Changelog
	}
	return nil
}

type AuthType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnabledFormAuth   bool                   `protobuf:"varint,1,opt,name=enabled_form_auth,json=enabledFormAuth,proto3" json:"enabled_form_auth,omitempty"`
	FormEditData      *AuthType_FormEditData `protobuf:"bytes,2,opt,name=form_edit_data,json=formEditData,proto3" json:"form_edit_data,omitempty"`
	EnabledQrcodeAuth bool                   `protobuf:"varint,3,opt,name=enabled_qrcode_auth,json=enabledQrcodeAuth,proto3" json:"enabled_qrcode_auth,omitempty"`
	QrcodeImage       []byte                 `protobuf:"bytes,4,opt,name=qrcode_image,json=qrcodeImage,proto3" json:"qrcode_image,omitempty"`     // qrcode image
	QrcodeExpire      uint64                 `protobuf:"varint,5,opt,name=qrcode_expire,json=qrcodeExpire,proto3" json:"qrcode_expire,omitempty"` // qrcode expire time
	EnabledOauth2Auth  bool   `protobuf:"varint,6,opt,name=enabled_oauth2_auth,json=enabledOauth2Auth,proto3" json:"enabled_oauth2_auth,omitempty"`
	Oauth2Url          string `protobuf:"bytes,7,opt,name=oauth2_url,json=oauth2Url,proto3" json:"oauth2_url,omitempty"`                              // oauth2 url
	Oauth2CallbackData []byte `protobuf:"bytes,8,opt,name=oauth2_callback_data,json=oauth2CallbackData,proto3" json:"oauth2_callback_data,omitempty"` // qrcode callback auth data
}

func (x *AuthType) Reset() {
	*x = AuthType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthType) ProtoMessage() {}

func (x *AuthType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthType.ProtoReflect.Descriptor instead.
func (*AuthType) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *AuthType) GetEnabledFormAuth() bool {
	if x != nil {
		return x.EnabledFormAuth
	}
	return false
}

func (x *AuthType) GetFormEditData() *AuthType_FormEditData {
	if x != nil {
		return x.FormEditData
	}
	return nil
}

func (x *AuthType) GetEnabledQrcodeAuth() bool {
	if x != nil {
		return x.EnabledQrcodeAuth
	}
	return false
}

func (x *AuthType) GetQrcodeImage() []byte {
	if x != nil {
		return x.QrcodeImage
	}
	return nil
}

func (x *AuthType) GetQrcodeExpire() uint64 {
	if x != nil {
		return x.QrcodeExpire
	}
	return 0
}

func (x *AuthType) GetEnabledOauth2Auth() bool {
	if x != nil {
		return x.EnabledOauth2Auth
	}
	return false
}

func (x *AuthType) GetOauth2Url() string {
	if x != nil {
		return x.Oauth2Url
	}
	return ""
}

func (x *AuthType) GetOauth2CallbackData() []byte {
	if x != nil {
		return x.Oauth2CallbackData
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State Status_State `protobuf:"varint,1,opt,name=state,proto3,enum=proto.Status_State" json:"state,omitempty"`
	Msg   string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetState() Status_State {
	if x != nil {
		return x.State
	}
	return Status_UNSPECIFIED
}

func (x *Status) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FileEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FileType     FileEntry_FileType `protobuf:"varint,2,opt,name=fileType,proto3,enum=proto.FileEntry_FileType" json:"fileType,omitempty"`
	Size         uint64             `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	FileMode     uint32             `protobuf:"varint,4,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`
	CreatedTime  uint64             `protobuf:"varint,5,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	ModifiedTime uint64             `protobuf:"varint,6,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	AccessedTime uint64             `protobuf:"varint,7,opt,name=accessed_time,json=accessedTime,proto3" json:"accessed_time,omitempty"`
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetFileType() FileEntry_FileType {
	if x != nil {
		return x.FileType
	}
	return FileEntry_FileTypeUNSPECIFIED
}

func (x *FileEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

func (x *FileEntry) GetCreatedTime() uint64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *FileEntry) GetModifiedTime() uint64 {
	if x != nil {
		return x.ModifiedTime
	}
	return 0
}

func (x *FileEntry) GetAccessedTime() uint64 {
	if x != nil {
		return x.AccessedTime
	}
	return 0
}

type DirEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileEntries []*FileEntry `protobuf:"bytes,1,rep,name=file_entries,json=fileEntries,proto3" json:"file_entries,omitempty"`
	Status      *Status      `protobuf:"bytes,100,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *DirEntry) GetFileEntries() []*FileEntry {
	if x != nil {
		return x.FileEntries
	}
	return nil
}

func (x *DirEntry) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type FileResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url             string                       `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	VideoResolution FileResource_VideoResolution `protobuf:"varint,2,opt,name=video_resolution,json=videoResolution,proto3,enum=proto.FileResource_VideoResolution" json:"video_resolution,omitempty"`
	ExpireTime      uint64                       `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	ResourceType    FileResource_ResourceType    `protobuf:"varint,4,opt,name=resource_type,json=resourceType,proto3,enum=proto.FileResource_ResourceType" json:"resource_type,omitempty"`
	Title           string                       `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Header          map[string]string            `protobuf:"bytes,6,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status          *Status                      `protobuf:"bytes,100,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *FileResource) Reset() {
	*x = FileResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResource) ProtoMessage() {}

func (x *FileResource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResource.ProtoReflect.Descriptor instead.
func (*FileResource) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *FileResource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileResource) GetVideoResolution() FileResource_VideoResolution {
	if x != nil {
		return x.VideoResolution
	}
	return FileResource_VideoResolutionUnspecified
}

func (x *FileResource) GetExpireTime() uint64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *FileResource) GetResourceType() FileResource_ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return FileResource_MediaResourceTypeUNSPECIFIED
}

func (x *FileResource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FileResource) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FileResource) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type AuthType_FormEdit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *AuthType_FormEdit) Reset() {
	*x = AuthType_FormEdit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthType_FormEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthType_FormEdit) ProtoMessage() {}

func (x *AuthType_FormEdit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthType_FormEdit.ProtoReflect.Descriptor instead.
func (*AuthType_FormEdit) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AuthType_FormEdit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthType_FormEdit) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AuthType_FormEdit) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type AuthType_FormEditData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormEdits []*AuthType_FormEdit `protobuf:"bytes,1,rep,name=form_edits,json=formEdits,proto3" json:"form_edits,omitempty"`
}

func (x *AuthType_FormEditData) Reset() {
	*x = AuthType_FormEditData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthType_FormEditData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthType_FormEditData) ProtoMessage() {}

func (x *AuthType_FormEditData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthType_FormEditData.ProtoReflect.Descriptor instead.
func (*AuthType_FormEditData) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1, 1}
}

func (x *AuthType_FormEditData) GetFormEdits() []*AuthType_FormEdit {
	if x != nil {
		return x.FormEdits
	}
	return nil
}

var File_proto_plugin_proto protoreflect.FileDescriptor

var file_proto_plugin_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x12,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x6c, 0x6f, 0x67, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x6c, 0x6f, 0x67, 0x22, 0x88, 0x04, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x6d, 0x41, 0x75, 0x74, 0x68, 0x12, 0x42,
	0x0a, 0x0e, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x45, 0x64, 0x69, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x66, 0x6f, 0x72, 0x6d, 0x45, 0x64, 0x69, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2e, 0x0a, 0x13, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x71, 0x72,
	0x63, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x11, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x71, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x71, 0x72, 0x63, 0x6f, 0x64, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x71, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x5f,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x71, 0x72,
	0x63, 0x6f, 0x64, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x32, 0x5f, 0x61, 0x75, 0x74,
	0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x4f, 0x61, 0x75, 0x74, 0x68, 0x32, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x61,
	0x75, 0x74, 0x68, 0x32, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6f, 0x61, 0x75, 0x74, 0x68, 0x32, 0x55, 0x72, 0x6c, 0x12, 0x30, 0x0a, 0x14, 0x6f, 0x61, 0x75,
	0x74, 0x68, 0x32, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x32, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x4a, 0x0a, 0x08, 0x46,
	0x6f, 0x72, 0x6d, 0x45, 0x64, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x1a, 0x47, 0x0a, 0x0c, 0x46, 0x6f, 0x72, 0x6d, 0x45,
	0x64, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x5f,
	0x65, 0x64, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x46, 0x6f, 0x72,
	0x6d, 0x45, 0x64, 0x69, 0x74, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x6d, 0x45, 0x64, 0x69, 0x74, 0x73,
	0x22, 0x97, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x50, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x75, 0x74,
	0x68, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x75, 0x74,
	0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x10, 0x04, 0x22, 0xbc, 0x02, 0x0a, 0x09, 0x46,
	0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x46, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x13, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x44, 0x69, 0x72, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x10, 0x02, 0x22, 0x66, 0x0a, 0x08, 0x44, 0x69, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x33, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x66,
	0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x8f, 0x05, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x4e, 0x0a, 0x10, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x45, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xad, 0x01,
	0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1e, 0x0a, 0x1a, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10,
	0x00, 0x12, 0x1b, 0x0a, 0x17, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x15,
	0x0a, 0x11, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x48, 0x44, 0x10, 0x03, 0x12, 0x16, 0x0a,
	0x12, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x51, 0x48, 0x44, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x48, 0x44, 0x10, 0x05, 0x22, 0x54, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a,
	0x1c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x75,
	0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x10, 0x03, 0x2a, 0x47, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x6f, 0x72, 0x6d, 0x45, 0x64, 0x69, 0x74, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x63, 0x61, 0x6e, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x10, 0x03, 0x42, 0x20, 0x5a, 0x1e,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x65,
	0x6d, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_proto_rawDescData = file_proto_plugin_proto_rawDesc
)

func file_proto_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_plugin_proto_rawDescData)
	})
	return file_proto_plugin_proto_rawDescData
}

var file_proto_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_plugin_proto_goTypes = []any{
	(AuthMethod)(0),                   // 0: proto.AuthMethod
	(Status_State)(0),                 // 1: proto.Status.State
	(FileEntry_FileType)(0),           // 2: proto.FileEntry.FileType
	(FileResource_VideoResolution)(0), // 3: proto.FileResource.VideoResolution
	(FileResource_ResourceType)(0),    // 4: proto.FileResource.ResourceType
	(*DriverPluginConfig)(nil),        // 5: proto.DriverPluginConfig
	(*AuthType)(nil),                  // 6: proto.AuthType
	(*Status)(nil),                    // 7: proto.Status
	(*FileEntry)(nil),                 // 8: proto.FileEntry
	(*DirEntry)(nil),                  // 9: proto.DirEntry
	(*FileResource)(nil),              // 10: proto.FileResource
	(*AuthType_FormEdit)(nil),         // 11: proto.AuthType.FormEdit
	(*AuthType_FormEditData)(nil),     // 12: proto.AuthType.FormEditData
	nil,                               // 13: proto.FileResource.HeaderEntry
}
var file_proto_plugin_proto_depIdxs = []int32{
	12, // 0: proto.AuthType.form_edit_data:type_name -> proto.AuthType.FormEditData
	1,  // 1: proto.Status.state:type_name -> proto.Status.State
	2,  // 2: proto.FileEntry.fileType:type_name -> proto.FileEntry.FileType
	8,  // 3: proto.DirEntry.file_entries:type_name -> proto.FileEntry
	7,  // 4: proto.DirEntry.status:type_name -> proto.Status
	3,  // 5: proto.FileResource.video_resolution:type_name -> proto.FileResource.VideoResolution
	4,  // 6: proto.FileResource.resource_type:type_name -> proto.FileResource.ResourceType
	13, // 7: proto.FileResource.header:type_name -> proto.FileResource.HeaderEntry
	7,  // 8: proto.FileResource.status:type_name -> proto.Status
	11, // 9: proto.AuthType.FormEditData.form_edits:type_name -> proto.AuthType.FormEdit
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_plugin_proto_init() }
func file_proto_plugin_proto_init() {
	if File_proto_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_plugin_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DriverPluginConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AuthType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FileEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DirEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FileResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AuthType_FormEdit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AuthType_FormEditData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_plugin_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_proto_depIdxs,
		EnumInfos:         file_proto_plugin_proto_enumTypes,
		MessageInfos:      file_proto_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_proto = out.File
	file_proto_plugin_proto_rawDesc = nil
	file_proto_plugin_proto_goTypes = nil
	file_proto_plugin_proto_depIdxs = nil
}
